services:
  db:
    image: mysql:8.1.0
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - app-network
    volumes:
      - static_data:/usr/share/nginx/static
      - media_data:/usr/share/nginx/media
    depends_on:
      - app

  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    networks:
      - app-network
    env_file:
      - ./app/.env
    depends_on:
      - db
    command: [ "gunicorn", "setup.wsgi:application", "-w", "2", "-b", ":8000" ]
  
  db-migrate:
    build:
      context: ./app
    volumes:
      - ./app:/app
    networks:
      - app-network
    env_file:
      - ./app/.env
    depends_on:
      - db
    profiles:
      - tools
    command: ["python", "manage.py", "migrate"]

  db-makemigrations:
    build:
      context: ./app
    volumes:
      - ./app:/app
    networks:
      - app-network
    env_file:
      - ./app/.env
    depends_on:
      - db
    profiles:
      - tools
    command: ["python", "manage.py", "makemigrations"]
  
  collectstatic:
    build:
      context: ./app
    volumes:
      - ./app:/app
    networks:
      - app-network
    env_file:
      - ./app/.env
    profiles:
      - tools
    command: ["python", "manage.py", "collectstatic", "--noinput"]

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  static_data:
  media_data: