# Generated by Django 3.2.25 on 2024-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='dork',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='google_dork',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
